MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./ex-3-1/build
	$(QUIET)$(MAKE) -C ./ex-3-2/build
	$(QUIET)$(MAKE) -C ./ex-3-3/build
	$(QUIET)$(MAKE) -C ./ex-3-4/build
	$(QUIET)$(MAKE) -C ./ex-3-5/build
	$(QUIET)$(MAKE) -C ./ex-3-6/build
clean:
	$(QUIET)$(CLEAN) -C ./ex-3-1/build
	$(QUIET)$(CLEAN) -C ./ex-3-2/build
	$(QUIET)$(CLEAN) -C ./ex-3-3/build
	$(QUIET)$(CLEAN) -C ./ex-3-4/build
	$(QUIET)$(CLEAN) -C ./ex-3-5/build
	$(QUIET)$(CLEAN) -C ./ex-3-6/build
