MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./chapter-1
	$(QUIET)$(MAKE) -C ./chapter-2
	$(QUIET)$(MAKE) -C ./chapter-3
	$(QUIET)$(MAKE) -C ./chapter-4

clean:
	$(QUIET)$(CLEAN) -C ./chapter-1
	$(QUIET)$(CLEAN) -C ./chapter-2
	$(QUIET)$(CLEAN) -C ./chapter-3
	$(QUIET)$(CLEAN) -C ./chapter-4
