MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./ex-4-4/build
	$(QUIET)$(MAKE) -C ./ex-4-5/build
	$(QUIET)$(MAKE) -C ./ex-4-11/build
	$(QUIET)$(MAKE) -C ./ex-4-12/build
clean:
	$(QUIET)$(CLEAN) -C ./ex-4-4/build
	$(QUIET)$(CLEAN) -C ./ex-4-5/build
	$(QUIET)$(CLEAN) -C ./ex-4-11/build
	$(QUIET)$(CLEAN) -C ./ex-4-12/build
