MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./ex-1-1/build
	$(QUIET)$(MAKE) -C ./ex-1-6/build
	$(QUIET)$(MAKE) -C ./ex-1-11/build
clean:
	$(QUIET)$(CLEAN) -C ./ex-1-1/build
	$(QUIET)$(CLEAN) -C ./ex-1-6/build
	$(QUIET)$(CLEAN) -C ./ex-1-11/build
