MAKE = make
CLEAN = make clean

all:
	$(MAKE) -C ./ex-1-1/build
	$(MAKE) -C ./ex-1-6/build
	$(MAKE) -C ./ex-1-11/build
clean:
	$(CLEAN) -C ./ex-1-1/build
	$(CLEAN) -C ./ex-1-6/build
	$(CLEAN) -C ./ex-1-11/build
