MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./ex-7-3/build
	$(QUIET)$(MAKE) -C ./ex-7-5/build
clean:
	$(QUIET)$(CLEAN) -C ./ex-7-3/build
	$(QUIET)$(CLEAN) -C ./ex-7-5/build
