MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./ex-5-1/build
	$(QUIET)$(MAKE) -C ./ex-5-3/build
	$(QUIET)$(MAKE) -C ./ex-5-4/build
	$(QUIET)$(MAKE) -C ./ex-5-7/build
	$(QUIET)$(MAKE) -C ./ex-5-8/build
	$(QUIET)$(MAKE) -C ./ex-5-10/build
	$(QUIET)$(MAKE) -C ./ex-5-13/build
clean:
	$(QUIET)$(CLEAN) -C ./ex-5-1/build
	$(QUIET)$(CLEAN) -C ./ex-5-3/build
	$(QUIET)$(CLEAN) -C ./ex-5-4/build
	$(QUIET)$(CLEAN) -C ./ex-5-7/build
	$(QUIET)$(CLEAN) -C ./ex-5-8/build
	$(QUIET)$(CLEAN) -C ./ex-5-10/build
	$(QUIET)$(CLEAN) -C ./ex-5-13/build
