MAKEFLAGS += --no-builtin-rules
QUIET = @
MAKE = make
CLEAN = make clean

all:
	$(QUIET)$(MAKE) -C ./ex-2-4/build
	$(QUIET)$(MAKE) -C ./ex-2-5/build
	$(QUIET)$(MAKE) -C ./ex-2-6/build
clean:
	$(QUIET)$(CLEAN) -C ./ex-2-4/build
	$(QUIET)$(CLEAN) -C ./ex-2-5/build
	$(QUIET)$(CLEAN) -C ./ex-2-6/build
